//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserWebApi.Application.Sources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UserWebApi.Application.Sources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FailedToCreateUser {
            get {
                return ResourceManager.GetString("FailedToCreateUser", resourceCulture);
            }
        }
        
        internal static string UserIsNotAuthorizedOrDeleted {
            get {
                return ResourceManager.GetString("UserIsNotAuthorizedOrDeleted", resourceCulture);
            }
        }
        
        internal static string FailedToUpdateUser {
            get {
                return ResourceManager.GetString("FailedToUpdateUser", resourceCulture);
            }
        }
        
        internal static string NotSupportedCondition {
            get {
                return ResourceManager.GetString("NotSupportedCondition", resourceCulture);
            }
        }
        
        internal static string UserAlreadyExistsWithThisLogin {
            get {
                return ResourceManager.GetString("UserAlreadyExistsWithThisLogin", resourceCulture);
            }
        }
        
        internal static string EnterNeededDtoValues {
            get {
                return ResourceManager.GetString("EnterNeededDtoValues", resourceCulture);
            }
        }
        
        internal static string FailedToFindUser {
            get {
                return ResourceManager.GetString("FailedToFindUser", resourceCulture);
            }
        }
        
        internal static string UserUpdatingPasswordIsFailed {
            get {
                return ResourceManager.GetString("UserUpdatingPasswordIsFailed", resourceCulture);
            }
        }
        
        internal static string CheckYourCurrentPassword {
            get {
                return ResourceManager.GetString("CheckYourCurrentPassword", resourceCulture);
            }
        }
        
        internal static string FailedToUpdateLoginOfUser {
            get {
                return ResourceManager.GetString("FailedToUpdateLoginOfUser", resourceCulture);
            }
        }
        
        internal static string NoAccessRights {
            get {
                return ResourceManager.GetString("NoAccessRights", resourceCulture);
            }
        }
        
        internal static string GettingActiveUsersIsFailed {
            get {
                return ResourceManager.GetString("GettingActiveUsersIsFailed", resourceCulture);
            }
        }
        
        internal static string GettingUserPersonalDataByLoginIsFailed {
            get {
                return ResourceManager.GetString("GettingUserPersonalDataByLoginIsFailed", resourceCulture);
            }
        }
        
        internal static string CheckYourCredentials {
            get {
                return ResourceManager.GetString("CheckYourCredentials", resourceCulture);
            }
        }
        
        internal static string GettingUserByLoginAndPasswordIsFailed {
            get {
                return ResourceManager.GetString("GettingUserByLoginAndPasswordIsFailed", resourceCulture);
            }
        }
        
        internal static string GettingAllUsersByDefiniteAgeIsFailed {
            get {
                return ResourceManager.GetString("GettingAllUsersByDefiniteAgeIsFailed", resourceCulture);
            }
        }
        
        internal static string FailedToDeleteUser {
            get {
                return ResourceManager.GetString("FailedToDeleteUser", resourceCulture);
            }
        }
        
        internal static string RecoveringUserByLoginIsFailed {
            get {
                return ResourceManager.GetString("RecoveringUserByLoginIsFailed", resourceCulture);
            }
        }
        
        internal static string UserInCookieAndAdminCheckingIsFailed {
            get {
                return ResourceManager.GetString("UserInCookieAndAdminCheckingIsFailed", resourceCulture);
            }
        }
    }
}
