//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserWebApi.Application.Sources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SuccessMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UserWebApi.Application.Sources.SuccessMessages", typeof(SuccessMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UserCreationIsSucceed {
            get {
                return ResourceManager.GetString("UserCreationIsSucceed", resourceCulture);
            }
        }
        
        internal static string UserUpdatingIsSucceed {
            get {
                return ResourceManager.GetString("UserUpdatingIsSucceed", resourceCulture);
            }
        }
        
        internal static string UserUpdatingPasswordIsSucceed {
            get {
                return ResourceManager.GetString("UserUpdatingPasswordIsSucceed", resourceCulture);
            }
        }
        
        internal static string UserLoginUpdatingIsSucceed {
            get {
                return ResourceManager.GetString("UserLoginUpdatingIsSucceed", resourceCulture);
            }
        }
        
        internal static string GettingActiveUsersIsSucceed {
            get {
                return ResourceManager.GetString("GettingActiveUsersIsSucceed", resourceCulture);
            }
        }
        
        internal static string GettingUserPersonalDataByLoginIsSucceed {
            get {
                return ResourceManager.GetString("GettingUserPersonalDataByLoginIsSucceed", resourceCulture);
            }
        }
        
        internal static string GettingUserByLoginAndPasswordIsSucceed {
            get {
                return ResourceManager.GetString("GettingUserByLoginAndPasswordIsSucceed", resourceCulture);
            }
        }
        
        internal static string GettingAllUsersByDefiniteAgeIsSucceed {
            get {
                return ResourceManager.GetString("GettingAllUsersByDefiniteAgeIsSucceed", resourceCulture);
            }
        }
        
        internal static string SoftDeletingIsSucceed {
            get {
                return ResourceManager.GetString("SoftDeletingIsSucceed", resourceCulture);
            }
        }
        
        internal static string FullDeletingIsSucceed {
            get {
                return ResourceManager.GetString("FullDeletingIsSucceed", resourceCulture);
            }
        }
        
        internal static string RecoveringUserByLoginIsSucceed {
            get {
                return ResourceManager.GetString("RecoveringUserByLoginIsSucceed", resourceCulture);
            }
        }
    }
}
